#          ╭──────────────────────────────────────────────────────────╮
#          │                      LazyGit Config                      │
#          ╰──────────────────────────────────────────────────────────╯

# GUI options
gui:
  # Customize the colorscheme
  # Catppuccin Mocha - Green
  # See: https://github.com/catppuccin/lazygit
  # See: https://github.com/catppuccin/lazygit/blob/main/themes-mergable/mocha/green.yml
  theme:
    activeBorderColor:
      - "#a6e3a1"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#16161f"
      - bold
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#a6e3a1"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

  # Customize the color highlights of the author
  authorColors:
    "rootiest": "#ff6e96"
    "*": "#b4befe"

  # Customize the color highlights of the branch
  branchColors:
    "docs": "#11aaff"
    "dev*": "#ebad6c"
    "main": "#af92fc"
    "master": "#af92fc"

  # Use latest Nerd Fonts glyphs
  # Requires: https://github.com/ryanoasis/nerd-fonts
  nerdFontsVersion: "3"

  # Show arrows for commits that diverge from the base branch
  showDivergenceFromBaseBranch: onlyArrow

  # How things are filtered when typing '/'
  filterMode: fuzzy

  spinner:
    # The frames of the spinner animation.
    frames:
      - "⠋"
      - "⠙"
      - "⠩"
      - "⠸"
      - "⠼"
      - "⠴"
      - "⠦"
      - "⠧"
    # The "speed" of the spinner in milliseconds.
    rate: 60

update:
  # One of: 'prompt' (default) | 'background' | 'never'
  method: background

  # Period in days between update checks
  days: 2

# Background refreshes
refresher:
  # File/submodule refresh interval in seconds.
  refreshInterval: 10

  # Re-fetch interval in seconds.
  fetchInterval: 60

os:
  # editPreset: nvim-remote
  open: xdg-open {{filename}} >/dev/null
  openLink: xdg-open {{link}} >/dev/null
  copyToClipboardCmd: printf "\033]52;c;$(printf {{text}} | base64)\a" > /dev/tty
  editPreset: nvim-remote
  editInTerminal: true

# Hide the startup popup
disableStartupPopups: true

# Don't prompt to return from subprocess when closing child processes (commitizen, etc)
promptToReturnFromSubprocess: false

git:
  paging:
    # Displays inline diff with syntax highlighting
    # Requires: https://github.com/Wilfred/difftastic
    externalDiffCommand: difft --color=always --display=inline --syntax-highlight=on --tab-width=2

customCommands:
  # Shortcut to prune branches that have been deleted from remote
  - key: "<c-p>" # Prune deleted remote branches
    command: "git remote prune {{.SelectedRemote.Name}}"
    context: "remotes"
    loadingText: "Pruning..."
    description: "prune deleted remote branches"

  # Shortcut to prune local merged branches that have been merged to master
  - key: "b" # Prune local merged branches
    command: "git branch --merged master | grep -v '^[ *]*master$' | xargs -r git branch -d"
    context: "localBranches"
    loadingText: "Pruning..."
    description: "prune local branches that have been merged to master"

  # Provides a commit tool for constructing commitizen commit messages
  #  using the conventional commit standard
  # Requires: https://commitizen.github.io/cz-cli/
  #  Recommend: https://www.npmjs.com/package/cz-conventional-emoji
  #  Alternative: https://www.npmjs.com/package/cz-conventional-changelog
  # Recommend: Use global hooks for commitizen
  #  See: https://github.com/commitizen/cz-cli?tab=readme-ov-file#conventional-commit-messages-as-a-global-utility
  # Alternative: Use local hooks for commitizen
  #  See: https://github.com/commitizen/cz-cli?tab=readme-ov-file#optional-running-commitizen-on-git-commit
  - key: "C" # Commitizen commit tool
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true

  # Requires: https://bun.sh/ and an OpenAI (or other AI) API key
  # See: https://github.com/m7medVision/lazycommit
  # Creates a menu of commit messages based on the diff between the current branch and master.
  # The menu is populated with commit messages generated by AI.
  - key: "<c-a>" # AI-generated commit message
    description: "pick AI commit"
    command: 'git commit -m "{{.Form.Msg}}"'
    context: "files"
    prompts:
      - type: "menuFromCommand"
        title: "Choose a commit message"
        key: "Msg"
        command: "bunx @m7medvision/lazycommit@latest"
        filter: '^(?P<number>\d+)\.\s(?P<message>.+)$'
        valueFormat: "{{ .message }}"
        labelFormat: "{{ .number }}: {{ .message | green }}"
